### ISSUE TITLE
I can compile nme app but intellij-haxe plugin shows hint errors in source code

### ISSUE THREAD

**Issue by djaonourside** [TiVo/intellij-haxe#381] opened 2016-01-13 22:19 UTC
I create haxe module and add nme library as project library pointing it's path in the haxe lib folder. Module compilation is ok(compile with NMML)  but I can see hint errors(red rectangles) in .hx files of project and nme library on the right side of editor(see attached pic). 
My stuff: win 7, intellij idea 14.1.6, intellij-haxe-14.1,  haxe 3.3.0, nme 5.5.13
![pic1](https://cloud.githubusercontent.com/assets/12369638/12309626/c9b19276-ba5c-11e5-9bba-e1d0efa87103.jpg)

**Comment by EBatTiVo** [comment] 2016-01-13 23:28
I've seen that error.  There's something wrong with how the plugin thinks the package name should be specified.  I haven't looked into it yet, but it does bother a number of folks.  I think the secondary error bars are because the nme package name is underspecified (according to the plugin).

**Comment by as3boyan** [comment] 2016-01-15 16:37
Yeah something wrong with package resolving, maybe Haxe SDK is not extracted properly.

**Comment by as3boyan** [comment] 2016-01-15 16:38
@djaonourside Are you sure that you correctly specified Haxe toolkit SDK in Project Settings?

**Comment by djaonourside** [comment] 2016-01-20 10:53
@as3boyan  Yes all sdk pathes are correct(compilation comes with success). The same issue I have on mac os.

**Comment by djaonourside** [comment] 2016-01-20 10:53
@as3boyan  Yes all sdk pathes are correct(compilation comes with success). The same issue I have on mac os.

**Comment by djaonourside** [comment] 2016-01-20 10:54
@as3boyan  Yes all sdk pathes are correct(compilation comes with success). The same issue I have on mac os.

**Comment by EBatTiVo** [comment] 2016-01-28 21:42
Duplicate of #387, which @EliasKu fixed.  It should be in the next release.

**Closed by EBatTiVo** 2016-01-28 21:42 UTC
Labels: bug, duplicate, Priority 4
