### ISSUE TITLE
[BUG] Cut/Copy/Paste not work

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#196] opened 2015-03-31 16:33 UTC
Build: [Build 0.8.1.1.TiVo.4](https://github.com/TiVo/intellij-haxe/blob/master/intellij-haxe.jar)
Idea: 14.1 IU-141.177
Project in demo for reproduce: [https://bitbucket.org/fzzr/hx.signal/.....](https://bitbucket.org/fzzr/hx.signal/src/97fe125e8106cbd5505acf153d21497c59e7c1bc/test/CopyPasteTest.hx?at=develop)

In my demo problem in `signal.add` and any `signal.any_method`. If I try to cut/copy any code with that line - it's not happening. Maybe troubles in CopyPasteProcessor and possible related issue #191.

![screen shot 2015-03-31 at 19 24 01](https://cloud.githubusercontent.com/assets/888526/6923633/932f3690-d7db-11e4-874d-004176005765.png)

![haxe plugin issue - copy-paste mov opt](https://cloud.githubusercontent.com/assets/888526/6923682/e9bd97ae-d7db-11e4-9b6b-c42f5cb3c62f.gif)

**Comment by as3boyan** [comment] 2015-03-31 16:58
Somebody said here, that IDEA 14.1 has changed API, and some things might not work, there is even pull request to update it to latest from contributor

**Comment by as3boyan** [comment] 2015-03-31 16:59
Might be related to CopyPasteProcessor

**Comment by as3boyan** [comment] 2015-03-31 17:00
@fzzr- How did you get it working in #191?

**Comment by as3boyan** [comment] 2015-03-31 17:10
BTW Help -> Show Log in Explorer, idea.log, may also contain stack trace for this error

**Comment by as3boyan** [comment] 2015-03-31 17:20
One of required things to get plugin compiled in IDEA 14.1 https://github.com/TiVo/intellij-haxe/pull/171

**Comment by fzzr-** [comment] 2015-03-31 18:01
@as3boyan 
>"@fzzr- How did you get it working in #191?"
There problem in `signal.`__`anyMethod`__ only. In #191 I did no sin that.
Need to check out class Signal.

Log:
```log
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.intellij.util.SmartList.get(SmartList.java:65)
	at com.intellij.plugins.haxe.lang.psi.HaxeClassResolveResult.specializeByParameters(HaxeClassResolveResult.java:153)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.tryResolveClassByTypeTag(HaxeResolveUtil.java:481)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResult(HaxeResolveUtil.java:448)
	at com.intellij.plugins.haxe.lang.psi.impl.AbstractHaxeTypeDefImpl.getTargetClass(AbstractHaxeTypeDefImpl.java:49)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResult(HaxeResolveUtil.java:418)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClass(HaxeReferenceImpl.java:408)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:97)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitExpression(HaxeVisitor.java:188)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitReferenceExpression(HaxeVisitor.java:430)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceExpressionImpl.accept(HaxeReferenceExpressionImpl.java:38)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.plugins.haxe.lang.psi.HaxeRecursiveVisitor.visitElement(HaxeRecursiveVisitor.java:29)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:95)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitTypePsiMixin(HaxeVisitor.java:655)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitType(HaxeVisitor.java:527)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeTypeImpl.accept(HaxeTypeImpl.java:38)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.plugins.haxe.lang.psi.HaxeRecursiveVisitor.visitElement(HaxeRecursiveVisitor.java:29)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:95)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitTypeOrAnonymous(HaxeVisitor.java:543)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeTypeOrAnonymousImpl.accept(HaxeTypeOrAnonymousImpl.java:38)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.plugins.haxe.lang.psi.HaxeRecursiveVisitor.visitElement(HaxeRecursiveVisitor.java:29)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:95)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitTypeTag(HaxeVisitor.java:551)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeTypeTagImpl.accept(HaxeTypeTagImpl.java:38)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.plugins.haxe.lang.psi.HaxeRecursiveVisitor.visitElement(HaxeRecursiveVisitor.java:29)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:95)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiField(HaxeVisitor.java:639)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitVarDeclarationPart(HaxeVisitor.java:575)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeVarDeclarationPartImpl.accept(HaxeVarDeclarationPartImpl.java:38)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.plugins.haxe.lang.psi.HaxeRecursiveVisitor.visitElement(HaxeRecursiveVisitor.java:29)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:95)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiField(HaxeVisitor.java:639)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitVarDeclaration(HaxeVisitor.java:571)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeVarDeclarationImpl.accept(HaxeVarDeclarationImpl.java:38)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.plugins.haxe.lang.psi.HaxeRecursiveVisitor.visitElement(HaxeRecursiveVisitor.java:29)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:95)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitClassBody(HaxeVisitor.java:124)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeClassBodyImpl.accept(HaxeClassBodyImpl.java:38)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.plugins.haxe.lang.psi.HaxeRecursiveVisitor.visitElement(HaxeRecursiveVisitor.java:29)
	at com.intellij.plugins.haxe.util.HaxeImportUtil$2.visitElement(HaxeImportUtil.java:95)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitPsiCompositeElement(HaxeVisitor.java:659)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitClass(HaxeVisitor.java:595)
	at com.intellij.plugins.haxe.lang.psi.HaxeVisitor.visitClassDeclaration(HaxeVisitor.java:128)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeClassDeclarationImpl.accept(HaxeClassDeclarationImpl.java:38)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:196)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
	at com.intellij.plugins.haxe.util.HaxeImportUtil.getReferencedClasses(HaxeImportUtil.java:92)
	at com.intellij.plugins.haxe.util.HaxeImportUtil.findUnusedImports(HaxeImportUtil.java:36)
	at com.intellij.plugins.haxe.ide.inspections.HaxeUnusedImportInspection.checkFile(HaxeUnusedImportInspection.java:72)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:151)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:309)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:304)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
2015-03-31 21:59:52,934 [1344699]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.1  Build #IU-141.177.4 
2015-03-31 21:59:52,934 [1344699]  ERROR - aemon.impl.PassExecutorService - JDK: 1.7.0_71 
2015-03-31 21:59:52,934 [1344699]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-03-31 21:59:52,934 [1344699]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
2015-03-31 21:59:52,934 [1344699]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2015-03-31 21:59:52,934 [1344699]  ERROR - aemon.impl.PassExecutorService - Last Action: EditorCut
```

**Comment by as3boyan** [comment] 2015-04-04 14:23
Thanks, this is much more precise. Checked line, seems fine. Still not sure why it happens.

**Comment by as3boyan** [comment] 2015-06-01 07:56
Still broken in 14.1.3

**Comment by as3boyan** [comment] 2015-06-01 08:26
Can't copy
```haxe
var c = {};
var d = 1;
```

Because of `resolveToParents` issues on project load

To reproduce https://github.com/TiVo/intellij-haxe/issues/282#issuecomment-107154940

Fixed in https://github.com/TiVo/intellij-haxe/pull/285
I hope this should fix this issue as well

**Comment by as3boyan** [comment] 2015-06-01 09:15
@fzzr- Please try http://www.filedropper.com/intellij-haxe jar for 14.1.3 latest with fix

**Comment by EBatTiVo** [comment] 2016-01-29 17:48
@fzzr - We think this was fixed 7 months ago.  Please re-open if you don't agree.

**Closed by EBatTiVo** 2016-01-29 17:48 UTC
Labels: bug, Priority 2

**Comment by Fzzr** [comment] 2016-01-29 17:57
You guys are pinging the wrong guy.
The one you want has a dash at the end of his name.
@fzzr- they think this was fixed 7 months ago. Please re-open if you don't agree.

**Comment by EBatTiVo** [comment] 2016-01-29 18:01
@fzzr - Sorry, I hit you up last year, too, IIRC.  It doesn't help that I usually put dashes in between callouts and comments.  :-)

**Comment by Fzzr** [comment] 2016-01-29 18:02
It happens every once in a while. No biggie.
