### ISSUE TITLE
Unresolved type (using generics) even though defined in the same package/file

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#103] opened 2015-01-11 15:07 UTC
Plugin version: [latest build](https://github.com/TiVo/intellij-haxe/blob/314e4e87dd12e8e2f18893cf105c04b5ef7f382e/intellij-haxe.jar).

![screen shot 2015-01-11 at 18 03 28](https://cloud.githubusercontent.com/assets/888526/5695574/4a6a1626-99bc-11e4-9aaa-0d2143739da5.png)

TIR: STB-7320

**Comment by EBatTiVo** [comment] 2015-02-04 05:47
We know there are some problems resolving generic types (types with parameters, such as ```<T>```).  I think this is an example of it.

**Comment by EBatTiVo** [comment] 2015-05-21 00:52
I wonder what we changed.  This seems to be working  ( IDEA 14.1.1, commit 46e5731f60295614b6621d7b877c67567d5afd57) :

```haxe
package TestGenerics;

class Issue103Test {
    public function new() {}
}

class Node {
    public function new() {}
}

class Output<T> {
    public function new() {}
}

class IntOutNode extends Node {
    private var a:Output<Dynamic>;
    private var b:Output<Dynamic>;

    private var inputs;
    private var outputs;

    //--------------Constructor--------------//

    public function new(x, y)
    {
        super();

        a = new ConstOutput<Int>(x);
        b = new ConstOutput<Int>(y);

        inputs = [a,b];
        outputs = [a,b];
    }
}

class ConstOutput<T> extends Output<T>
{
    var data:Dynamic;
    var changed:Bool;

    public function new(?data)
    {
        super();
        this.data = data;
    }

    override function set_data(v)
    {
        if (data == null)
            return data;

        data = v;
        changed = true;

        return v;
    }
}
```

**Comment by EBatTiVo** [comment] 2015-05-21 05:02
Well, I chased it for a bit, but going back to the commit referenced in the report and I don't see the bug with the sources above and IDEA 13.1.5.

@fzzr- If you have some other code that shows the problem, please post it.

**Comment by as3boyan** [comment] 2015-06-01 07:24
Talking about generics, it's hard to use HaxeFlixel in IDEA, because of it, it's really great test for generics.

**Comment by EBatTiVo** [comment] 2015-06-04 17:15
@fzzr- @as3boyan I'm working on generics right now.  I don't have a reproducible case for this issue, though.

**Comment by as3boyan** [comment] 2015-06-04 17:36
That's great. I am glad to hear it.

**Comment by EBatTiVo** [comment] 2015-06-16 02:06
Closing, because it works for the code given above and there is no other reproducible case.

Works for me.

**Closed by EBatTiVo** 2015-06-16 02:06 UTC
Labels: bug, Priority 2, Works For Me
