### ISSUE TITLE
Wrong behaviour of Optimize Import

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#191] opened 2015-03-30 13:28 UTC
Build: [Build 0.8.1.1.TiVo.4](https://github.com/TiVo/intellij-haxe/blob/master/intellij-haxe.jar)

Need to filtering similar import-items. In my demo I did copy-paste and get a dialog with many of the same items. After it I was try to Optimize Imports - get no wanted result :(

![haxe plugin issue mov opt](https://cloud.githubusercontent.com/assets/888526/6897057/9468db52-d6f9-11e4-9744-d50d274dc06d.gif)

**Comment by as3boyan** [comment] 2015-03-30 15:23
Ok, CopyPasteProcessor doesn't checks for duplicate items and Optimize imports doesn't detects duplicate imports. Thanks.

**Comment by as3boyan** [comment] 2015-03-30 15:24
I'm curious is this an IDEA 14?

**Comment by as3boyan** [comment] 2015-03-30 15:52
Ok, roger that

**Comment by fzzr-** [comment] 2015-03-30 16:10
Yes, latest Idea 14.

**Comment by as3boyan** [comment] 2015-03-30 16:12
I added a check for duplicate items, about Optimizing imports - can't reproduce it, for flash.display.Sprite it works fine, it may not work if reference is unresolved, but it seems to be resolved on your gif.

**Comment by as3boyan** [comment] 2015-03-31 16:56
Please try to optimize this:

```haxe
import flash.display.Sprite
import flash.display.Sprite
import flash.display.Sprite
```

**Comment by fzzr-** [comment] 2015-03-31 18:10
Magic! It works but how?!
I can reproduce this issue only in that project: [https://bitbucket.org/fzzr/hx.signal/.....](https://bitbucket.org/fzzr/hx.signal/src/97fe125e8106cbd5505acf153d21497c59e7c1bc/?at=develop)

**Comment by as3boyan** [comment] 2015-04-02 17:23
Is that specific commit or I can download just latest `develop` branch from downloads section?

**Comment by fzzr-** [comment] 2015-04-02 18:13
Take the last commit.

**Comment by fzzr-** [comment] 2015-04-03 22:24
@as3boyan 
That's new:
![screen shot 2015-04-04 at 1 21 35](https://cloud.githubusercontent.com/assets/888526/6989803/1b265fbc-da69-11e4-9b17-9e3e1c53a1f6.png)

Maybe related issues: #199 & #200.

**Comment by as3boyan** [comment] 2015-04-04 11:33
Seems like this doesn't works
```haxe
import String.fromCharCode in f;

class Main2 {
    static function main() {
        var c1 = f(65);
        var c2 = f(66);
        trace(c1 + c2); // AB
    }
}
```

**Comment by as3boyan** [comment] 2015-04-04 11:36
I think it doesn't supported yet.

**Comment by EBatTiVo** [comment] 2015-04-21 07:06
Appears fixed and merged.  @fzzr- Please test and re-open if this bug is not fixed.

**Closed by EBatTiVo** 2015-04-21 07:06 UTC
