### ISSUE TITLE
[haxe javascript] compilation fails but no error is shown (after update to 0.9)

### ISSUE THREAD

**Issue by ophibox** [TiVo/intellij-haxe#160] opened 2015-03-17 13:22 UTC
Hi, after updating the Haxe plugin to 0.9 (idea 14), when I build/make a project, the console says I have errors but doesn't display them anymore. Reverted to 0.8 and it works.

![0.9 console output](http://image.noelshack.com/fichiers/2015/12/1426598388-errorlog.png)
![0.8 console output](http://image.noelshack.com/fichiers/2015/12/1426598388-errorlog-old.png)

Even though it displayed the error as a warning, it was still better than nothing.
(and BTW double clicking the "error" warning does not jump to the source file/error line)

TIR: STB-9363

**Comment by EBatTiVo** [comment] 2015-04-22 00:47
Related to #129.  Duplicate of #180 (or vice versa, but that bug has more discussion).

**Closed by EBatTiVo** 2015-04-22 00:47 UTC
Labels: bug, duplicate

**Comment by EBatTiVo** [comment] 2015-04-28 19:51
Fixed.  Will be in the next release after 0.9.3.  Please re-open if it recurs.
