### ISSUE TITLE
Long input block when completing

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [TiVo/intellij-haxe#243] opened 2015-04-18 10:34 UTC
Using Idea 14.1.1 and intellij-haxe 0.9.3. When I complete something, like this:

```
function test() {
    v|
}
```

the popup with completion comes up. When I try to input more characters the IDE freezes for a few seconds (feels very long, but I guess it is just a few seconds).
(The completion gives "var" as the first suggestion).

**Comment by EBatTiVo** [comment] 2015-04-18 16:22
Can you please characterize this a bit more?  Does the freeze appear before or after the completion popup?  Is the second character blocked?  Does it only occur after the second character is pressed?  After it is displayed? 

What are your project settings?
What is the version of Haxelib and the Haxe compiler that you are using?
How many, and which libraries are set up for your project? (File->Project Structure->Libraries [tab])
Which OS are you using?

This doesn't happen for me with either a barebones project, or a very large one.  (Ubuntu 12.04, Idea 14.1 (141.177), Haxelib 3.1.0-rc.4, Haxe 3.1.3 (customized)).

This is likely a duplicate of #230.

**Comment by RudolfVonKrugstein** [comment] 2015-04-18 16:53
To describe the moment of blocking more exacty, I type:

```
function test() {
  va|
}
```

(cursor at |), I get his pricture (the a is already pressed, but is not yet displayed):
![image](https://cloud.githubusercontent.com/assets/1104805/7216301/c7e77c58-e5fa-11e4-8deb-539e69b9144f.png)
And it is blocking for a few seconds.

Versions used:
haxe:
3.1.3

haxelib:
Haxe Library Manager 3.2.0-rc.3 - (c)2006-2015 Haxe Foundation

I do not know which proejct settings you need. Under Project Settings -> Modules I choose openfl and linux64 target (build works).

And if I change that to "hxml" and choose a old file which was generated from vaxe a while ago, the block disappears. So that is a workaround for me for now.

**Comment by EBatTiVo** [comment] 2015-04-18 17:35
How many, and which, libraries do you have included in your project?  (Navigate to "File->Project Structure->Libraries [tab]".  I'm looking for the list that appears in the Center column -- including those that were added automatically by haxelib.)  

Actually, the easier way is just to post the .ipr and .iml files from your project.  If you don't have an .ipr file, then post .idea/modules.xml, .idea/workspace.xml, idea/compiler.xml, and .idea/haxe.xml. (http://www.pastebin.com or http://www.dropbox.com are fine for posting these.)

Since you're selecting linux64 as the project target, I presume you're running on Linux.

**Comment by RudolfVonKrugstein** [comment] 2015-04-18 19:15
The libraries part of my project settings is empty (I have recreated to the project few days ago and not re-added the libraries). But the libraries in my project.xml are:

* actuate
* unifill
* hscript
* tink_core
* polygonal-ds
* spritesheet
* monax
* svg
* golems
* 4 more local libraries

modules.xml:
http://pastebin.com/raw.php?i=d10cVrEG

iml file:
http://pastebin.com/raw.php?i=mjUggabC

**Comment by RudolfVonKrugstein** [comment] 2015-04-18 19:43
I was wondering if the big codebase of my project would be causing the problem. So i created a idea project for PiratePig (openfl sample) and set the project structure to "openfl, linux64". The problem occurs in that project too

**Comment by EBatTiVo** [comment] 2015-04-21 23:37
Dupllicate of #230.

**Closed by EBatTiVo** 2015-04-21 23:37 UTC
Labels: bug, duplicate
