### ISSUE TITLE
Hangs on completion

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#122] opened 2015-02-12 18:32 UTC
To reproduce:  Trigger completion on a haxe source file.  (May be toolkit dependent.)

I think it's related to my implementation of Haxe compiler completion contributor, it waits for some response, and only unblocks when I kill `haxe` process two times

TIR: STB-7737

**Comment by EBatTiVo** [comment] 2015-02-12 18:34
HI Boyan,  Can you give more details here?

**Comment by as3boyan** [comment] 2015-02-12 19:25
It hangs when it attempts to get Meta tags and other stuff

**Comment by EBatTiVo** [comment] 2015-02-12 19:27
So, how do I reproduce this?

**Comment by as3boyan** [comment] 2015-02-12 19:31
```java
//process.waitFor(); used to block IDE for some reason
```

**Comment by as3boyan** [comment] 2015-02-12 19:32
https://github.com/EBatTiVo/intellij-haxe/blob/ClassHierarchy/src/com/intellij/plugins/haxe/haxelib/HaxelibCommandUtils.java#L152-152

**Comment by as3boyan** [comment] 2015-02-12 19:42
http://stackoverflow.com/questions/5483830/process-waitfor-never-returns

**Comment by as3boyan** [comment] 2015-02-12 19:46
http://bytes.com/topic/java/answers/829186-question-about-process-waitfor#post3311115

**Comment by as3boyan** [comment] 2015-02-12 19:49
@EBatTiVo To me, it was very easy to reproduce - just trigger completion in some Haxe file and that's all. We might have different JDKs, not sure.

**Comment by EBatTiVo** [comment] 2015-02-12 20:06
I didn't try to trigger completion or dup this.  I was just trying to get you to put some details in place so that I can try it later.  Now that you've fixed it, it's not so necessary, but better descriptions keeps down the number of issues that other people file... at least, assuming they actually search for related issues before writing new bug reports.

**Comment by grisevg** [comment] 2015-02-17 14:53
I have same problem in my project. I think it depends on actual source base you doing auto-complete on.

Is it fixed now? I'd like to test it.

**Comment by as3boyan** [comment] 2015-02-17 16:27
Yeah it's fixed.

**Comment by EBatTiVo** [comment] 2015-04-21 03:23
Closing, since the last comment says it's fixed.

**Closed by EBatTiVo** 2015-04-21 03:23 UTC
Labels: bug
