### ISSUE TITLE
idea14 plugin: in module settings - OpenFL arguments don't saved and always empty

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#179] opened 2015-03-21 15:37 UTC
https://github.com/eliasku
idea14 plugin: in module settings - OpenFL arguments don't saved and always empty

**Comment by jasonsturges** [comment] 2015-03-21 19:17
This sounds like my issue #74 - OpenFL arguments not persisted in module settings #74

**Comment by EBatTiVo** [comment] 2015-03-23 06:18
Duplicate of #74.

**Closed by EBatTiVo** 2015-03-23 06:18 UTC
Labels: duplicate
