### ISSUE TITLE
Imports adding before package

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#104] opened 2015-01-11 15:20 UTC
Plugin version: [latest build](https://github.com/TiVo/intellij-haxe/blob/314e4e87dd12e8e2f18893cf105c04b5ef7f382e/intellij-haxe.jar).

Step 0:
_look, we have a comment under the package_
![screen shot 2015-01-11 at 18 10 55](https://cloud.githubusercontent.com/assets/888526/5695632/fb371dd6-99bd-11e4-9a95-66f6be53374e.png)

Step 1:
![screen shot 2015-01-11 at 18 11 52](https://cloud.githubusercontent.com/assets/888526/5695634/0f94f69a-99be-11e4-939f-41442ab20226.png)

Step 2:
_wtf:)_
![screen shot 2015-01-11 at 18 12 06](https://cloud.githubusercontent.com/assets/888526/5695641/4af9e0e2-99be-11e4-942a-60740f2ccaf4.png)

**Comment by as3boyan** [comment] 2015-01-13 18:52
I will need to look into this.

**Comment by EBatTiVo** [comment] 2015-02-04 07:34
Duplicate of the unfinished work from Issue #10.

**Closed by EBatTiVo** 2015-02-04 07:34 UTC
Labels: bug, duplicate
