### ISSUE TITLE
unresolved symbol, because of conditional compilation instructions

### ISSUE THREAD

**Issue by shalmu** [TiVo/intellij-haxe#463] opened 2016-05-10 10:23 UTC
When writing this:

```haxe
import haxe.io.Output;
class Something{
    public function answer(buf:Output){
        buf.writeFloat(.42);
    }
}
```

I see "writeFloat" "unresolved symbol", because in Output there is
```haxe
public #if !(flash || python) inline #end function writeFloat( x : Float ) {
		writeInt32(FPHelper.floatToI32(x));
	}
```
looks like Haxe plugin is unable to make sense of these "#if...#end".

I can fix the problem by newlining the # section:
```haxe
public  
#if !(flash || python) inline #end 
function writeFloat( x : Float ) {
		writeInt32(FPHelper.floatToI32(x));
	}
```
But I should not mess with factory lib files, should I...

**Comment by EBatTiVo** [comment] 2016-05-10 18:38
Duplicate of #417,  #115, #29, #121.

No, you shouldn't have to mess with factory libs.  However, it's one way out of this issue.  As you can see by the reading the comments in the duplicates, it's a difficult problem to crach.  Maybe somebody can write a library preprocessor that fixes this locally.  It makes for other issues (such as line numbers being incorrect) when issues are filed against modified libraries.  :-/

At any rate, I'm going to close this because we don't want to keep a bunch of the same bug around.

**Closed by EBatTiVo** 2016-05-10 18:38 UTC
Labels: bug, duplicate
