### ISSUE TITLE
HXCPP debug does not start

### ISSUE THREAD

**Issue by arthurferrai** [TiVo/intellij-haxe#483] opened 2016-09-22 20:17 UTC
I've configured my environment to debug hxcpp application following wiki instructions, but when I press debug button, nothing happens. Is debugging using IntelliJ possible at all?

**Comment by EBatTiVo** [comment] 2016-09-22 21:02
Yes, it is possible and working for members of our team.

Are you sure that your application compiled correctly?  Depending upon what "nothing happens" means to you, it may be that your compilation didn't succeed, or that you haven't set up the proper Debug configuration (in IDEA, via the Run->Debug... menu item.  We've also seen improper/missing SDK configuration (File->Project Settings...) silently fail to execute.  Make sure that the Run... configuration works, then debugging should start correctly.  If Run... doesn't work, Debug... won't either.

If Run... works and Debug... does not, did you add the required code to your application's Main function?  See https://github.com/TiVo/intellij-haxe#use-the-hxcpp-debugger.

**Comment by arthurferrai** [comment] 2016-09-23 11:46
My app compiles correctly (I can click "Run" and it starts correctly). My debug settings are these:
<img width="1339" alt="screen shot 2016-09-23 at 08 38 59" src="https://cloud.githubusercontent.com/assets/5352649/18784599/931c3f48-8169-11e6-8e13-0acbf2e197cf.png">

I'm using debug calling on main function:
```
public function new()
	{
		super();
		new debugger.HaxeRemote(true, "localhost", 6972);
		addChild(new FlxGame(gameWidth, gameHeight, initialState, zoom, framerate, framerate, skipSplash, startFullscreen));
	}
```

Program starts debug and tries to connect (and never succeed).

When I say "nothing happens", I mean exactly that. Literally nothing happens (as if I never clicked the button).

I'm using IntelliJ Idea CE 15.0.6 on OSX.

**Comment by EBatTiVo** [comment] 2016-09-23 17:00
I'm confused by the antinomy caused by these two mutually exclusive statements: "Program starts debug and tries to connect..." and "Literally nothing happens..."

So... it sounds like when you press the Debug button your app does start, but IDEA doesn't show either the logging panel or the debug panel.  

Have you set any breakpoints??  It may be that your app is just running and having no reason to break, the debugger doesn't bring up the debug window.  (The debugger does NOT stop the program just because you started it.  A breakpoint must be hit.  (There is a bug -- in the hxcpp debugger -- where a program won't stop when the pause button is pressed unless a breakpoint was hit first.)

And another thought just occurred: You are using the C++ target for your project, right?  Because that's the only target (that I know of) that works right now.  (Flash used to -- a looooong time ago.)

**Comment by EBatTiVo** [comment] 2016-09-23 17:28
Another thought: When "nothing happens," look at the status bar at the bottom of the IDEA window.  Sometimes, warnings are displayed there and are easily missed.

**Comment by arthurferrai** [comment] 2016-09-23 18:58
Sorry for the confusion: When I press "Run", program runs and debug library tries to connect. When I press "Debug", nothing happens. Nothing really. No console message, no program trying to run... nothing.

Shouldn't start debugger with `new debugger.HaxeRemote(true, "localhost", 6972);` start the debugger paused?

Yes, I'm using C++ target.

Just to be sure: I need to just press "Debug" button to debug the program or "Run" and then "Debug" buttons?

**Comment by EBatTiVo** [comment] 2016-09-23 21:20
> Shouldn't start debugger with new debugger.HaxeRemote(true, "localhost", 6972); start the debugger paused?

Yes, it should; it's a known bug that it doesn't.  The workaround is simple: set a breakpoint on the line after `new debugger.HaxeRemote`.

> Just to be sure: I need to just press "Debug" button...

That is the correct workflow.  The debug launcher should start up a listener and then wait for your program to connect.  You should have a console pane (normally gets obscured by the debug pane) pop up that shows basically the same thing as when you press 'Run'. (e.g. Lime starts and then runs your program.)

All of that said, you can't just use the latest hxcpp-debug library either.  It has been upgraded to v1.2, and the plugin still only talks the protocol from 1.1.  Be sure you're running the right version.  (See the first paragraph of the debugger section of our main page: https://github.com/TiVo/intellij-haxe#use-the-hxcpp-debugger for how to do that.)

You can test that the debugger is working from your program without using IDEA.  There is a command-line debugger shipped with hxcpp-debugger that can connect to your program.  It's a lot like running gdb, but can verify that the debugging code in your program is working correctly and isolates the issues to IDEA. (https://github.com/HaxeFoundation/hxcpp-debugger/wiki/Getting-started.)

Finally, (and I'm not sure of this at all - I was unable to test it quickly because of my environment) it may be that you can't start the debugger in your app's `new` function.  Try placing the debugger startup in the static 'main' function of your app class.

**Comment by arthurferrai** [comment] 2016-09-24 15:35
Using `new debugger.Local(true);` it stops as expected (using "Run" button):
<img width="1238" alt="screen shot 2016-09-24 at 12 32 21" src="https://cloud.githubusercontent.com/assets/5352649/18809488/f7eb54d8-8252-11e6-8f77-197a69b992f8.png">

Also, my hxcpp-debugger version looks correct:
```
$ haxelib path hxcpp-debugger
/usr/local/lib/haxe/lib/hxcpp-debugger/git/
-D hxcpp-debugger=1.1.0
/usr/local/lib/haxe/lib/hxcpp/3,3,49/
-D hxcpp=3.3.49
```

**Comment by EBatTiVo** [comment] 2016-09-24 18:14
@EliasKu: You run on a mac.  Did you have any issues with getting the debugger to run?

**Comment by arthurferrai** [comment] 2016-09-27 14:07
Just a suggestion: should I do a downgrade on IntelliJ IDEA? I'm trying with version 15.0.6

**Comment by eliasku** [comment] 2016-09-27 15:28
@arthurferrai @EBatTiVo seems like we have 1.1 protocol and other versions of hxcpp-debugger throw exceptions. Just for test I've created ExeRunningState to run debugger from hxml file. After downgrading hxcpp-debugger to protocol_v1.1, debugger is successfully connected, but breakpoints don't work. Should we upgrade protocol version?

**Comment by arthurferrai** [comment] 2016-09-27 17:13
@eliasku My hxcpp-debugger is on 1.1 version. My problem is that debug doesn't start on IntelliJ when I click "Debug" button (terminal debug works as expected).

**Comment by EBatTiVo** [comment] 2016-09-27 20:09
@arthurferrai: I wouldn't necessarily downgrade, but it might be a useful test.  You can't pick up Mac builds of previous versions (e.g. 15.0.4, 15.0.3) on the web, but you can pick up the latest 14.1.  In the end, though, it's not likely the issue.  More likely, that you've got to pick up the github build at the proper tag.  But, then again, @eliasku says that breakpoints aren't working.  We will have to take a look.

@eliasku: I think we should upgrade the debugger to the new protocol.  It's not super-simple, though, for two reasons:  1) The protocol code (in Haxe) isn't compiling to Java correctly, so we're using a checked-in version of the generated code; the UCSC guys fixed it (look for a PR from @tekgek) but I haven't pulled their changes yet because it requires that the compiler guys take a few changes as well.  2) The way that data is passed changed between protocol versions 1.1 and 1.2 from a recursive structure to an array structure (which I find more understandable).  So, we've not only got to update the Haxe code generation, but we've got to rewrite the data parsing.  It will take several days worth of effort, but it's very doable, provided we get the time.

**Comment by arthurferrai** [comment] 2016-09-27 20:42
@EBatTiVo Installed IntelliJ Idea 14.1. Exactly same behavior, "Debug" button does absolutely nothing. Do I need special configuration for this to work?

**Comment by EBatTiVo** [comment] 2016-09-27 22:14
No, you should not need a special configuration.  Your app should be running even if the debugger doesn't connect.  You don't even seem to have that, so I'm trying to think of why an app might not run from the Debug menu when it runs just fine from the Run menu.  (And, I'm not much of a Mac user, so I don't know the platform specifics.)  If you remove the HaxeDebug.Remote line from your app, does it execute?

Other random thoughts:
If the app is starting, it is most likely that the plugin and the debugger are not completing the startup handshake.  That can happen if the protocols don't match, but it can also happen if there are socket issues.  
(You don't have a firewall keeping processes from talking to localhost, do you?  And DNS -- nslookup -- resolves localhost to 127.0.0.1, right?   You can try substituting 127.0.0.1 for localhost in the HaxeDebug.Remote() call.)

**Comment by EBatTiVo** [comment] 2016-09-27 22:33
@arthurferrai:  If the app will run from the "Debug..." menu without HaxeDebug.Remote(), you will want to check your git branch (as opposed to haxelib).
```git branch``` should give you: 
```
   master
 * protocol_v1.1
```
If it does not:
```
  $ cd <your_local_git_clone>
  $ git pull origin protocol_v1.1
  From https://github.com/HaxeFoundation/hxcpp-debugger
   * branch            protocol_v1.1 -> FETCH_HEAD
  Already up-to-date.
  $ git checkout protocol_v1.1
  Branch protocol_v1.1 set up to track remote branch protocol_v1.1 from origin.
  Switched to a new branch 'protocol_v1.1'
  $ haxelib git hxcpp-debugger <your_local_git_clone> protocol_v1.1
```
Then you will definitely have the proper version of the debugger.

**Comment by arthurferrai** [comment] 2016-09-28 13:08
Ok, all details:

My OS X is 10.11.6.

My IntelliJ IDEA is on version 14.1.7.

(Just to note, I'm using HaxeFlixel, but since it runs on top of OpenFL, it _should_ work as expected)

My "Run/Debug Configurations" is as follows:
- **Name** is default, **Share** is unmarked and **Single Instance Only** is unmarked
- **Module** has the name of my project (and it's the only available option)
- **Alternative Executable** is unmarked
- **Custom file to run** is unmarked
- **Debugger Listen Port** is 6972, with **Remote Debugging** marked
- **Before Launch** is empty
- **Show this page** is unmarked

My "Project Structure/Module" settings are as follows:
- **Sources** tab has all my project files
- **Dependencies** tab has all my project libraries (no one is marked to Export) and **Dependencies storage format** has option **IntelliJ IDEA (.iml)** marked
- **Haxe** tab has:
  - **Compile with** marked with **OpenFL**
  - **Target** marked with **Mac OS**
  - **Project Macros** empty
  - **OpenFL arguments** has "-debug"
  - **OpenFL Project XML** has the path of my "Project.xml" file
  - **Skip compilation** is unmarked

Using entry-point as follows:
```
	public function new()
	{
		super();
		new debugger.Local(true);
		addChild(new FlxGame(gameWidth, gameHeight, initialState, zoom, framerate, framerate, skipSplash, startFullscreen));
	}
```

When I click on "Run", IDEA shows me the "Run" output window with this content (excluding Lime stuff):

```
Running command: RUN
 - Changing directory: export/mac64/cpp/bin/spjam2016.app/Contents/MacOS
 - Running command: ./spjam2016 -verbose -livereload
2016-09-28 09:41:02.881 spjam2016[7225:526708] 09:41:02.880 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
2016-09-28 09:41:03.057 spjam2016[7225:526708] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/22/w3drmwfn4mg_m4g8h32wn2vr0000gn/T/com.example.myapp.savedState

-=- hxcpp built-in debugger in command line mode -=-
-=-      Use 'help' for help if you need it.     -=-
-=-                  Have fun!                   -=-

Thread 0 stopped in Main.new() at Main.hx:22.

1> 
```
Which indicates me that local debug works as expected.


When I click "Debug", nothing happens (my app doesn't run and there's no log report on IDEA event log window, nor any other window).

Now, I changed my entry point to this:

```
	public function new()
	{
		super();
		new debugger.HaxeRemote(true, "127.0.0.1", 6972);
		addChild(new FlxGame(gameWidth, gameHeight, initialState, zoom, framerate, framerate, skipSplash, startFullscreen));
	}
```

When I click on "Run", IDEA shows me the "Run" output window with this content (again, excluding Lime stuff):

```
Running command: RUN
 - Changing directory: export/mac64/cpp/bin/spjam2016.app/Contents/MacOS
 - Running command: ./spjam2016 -verbose -livereload
2016-09-28 10:07:25.345 spjam2016[7451:540415] 10:07:25.345 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
2016-09-28 10:07:25.451 spjam2016[7451:540415] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/22/w3drmwfn4mg_m4g8h32wn2vr0000gn/T/com.example.myapp.savedState
Debugger:Starting App side debugger support.
Debugger:Failed to connect to debugging server at 127.0.0.1:6972 : EOF
Debugger:Trying again in 3 seconds.
Debugger:Failed to connect to debugging server at 127.0.0.1:6972 : EOF
Debugger:Trying again in 3 seconds.
```
(Debugger failure keeps repeating while program is running)

When I click "Debug", nothing happens again.

**Comment by EBatTiVo** [comment] 2016-09-28 19:58
My current suspicion is that you are getting an exception that is stopping the whole debug process from running.  Can you please open your Java console (I believe, on a mac, that you do that by opening the Java Control Panel "System Preferences->Java->(opens new window)->Advanced->Show console"), and post any exceptions that occur when you press the Debug button?

**Comment by arthurferrai** [comment] 2016-09-29 02:38
@EBatTiVo I've activated Java console as you said, but it won't open when I start IntelliJ IDEA. On IDEA log (~/Library/Logs/IdeaIC14), there are no changes when I press debug button.

**Comment by EBatTiVo** [comment] 2016-09-29 02:59
@arthurferrai I'm at a loss.  I can't think of any other reasons why you might be getting this behavior.  I'll keep thinking about it.  

It's looking like a debugging session is in order, but in order to do that somebody is going to have to duplicate the behavior you're seeing.  I do have a mac that I could try on; it's the time I don't have much of.

In the mean-time, if you feel particularly inclined, you could set up a dev environment for the plugin and try it yourself.  See the CONTRIBUTING page for how to do that (https://github.com/TiVo/intellij-haxe/blob/master/CONTRIBUTING.md).  If you do, the classes you want to look at are in https://github.com/TiVo/intellij-haxe/tree/master/src/14.1/com/intellij/plugins/haxe/runner/debugger.  If you have questions about that code, we'll try and answer them.

(This isn't to put you off, rather to get you help from more knowledgeable folks that may be out there:)
There is an #IRC channel that has (should have) a lot more traffic: http://old.haxe.org/com/meeting/irc
You may also get more informed help (about IDEA anyway) from the IDEA forums: http://blog.jetbrains.com/idea/2012/05/get-involved-into-intellij-idea-community/

**Comment by arthurferrai** [comment] 2016-09-29 12:47
@EBatTiVo I'll try to debug plugin to see if I can discover anything. Should I try on "master" branch?

**Comment by arthurferrai** [comment] 2016-09-29 13:57
@EBatTiVo Is it really necessary to install flex sdk?

**Comment by EBatTiVo** [comment] 2016-09-29 17:03
Yes, the master branch is the most up-to-date and has all of the approved changes.  If you find you want to make new changes, then make yourself a work branch.  The CONTRIBUTING.md doc has the workflow instructions.

**Comment by EBatTiVo** [comment] 2016-09-29 17:05
Not unless you are going to mess with the BNF or parsing.

**Comment by arthurferrai** [comment] 2016-09-29 17:13
@EBatTiVo I had problems trying to debug plugin using CE, but worked when using Ultimate.
After that, I downloaded jar file from IDEA site and installed on Ultimate edition, and it kinda works as expected. Is it incompatible with CE?

**Comment by EBatTiVo** [comment] 2016-09-29 17:56
You mean the Haxe debugger is working correctly for you, now that you're using Ultimate and the 0.9.10 released jar file?  Or do you mean that you can debug the plugin, but you still haven't solved your problem of debugging your app?

Some community folks use the IDEA-CE, but none of the developers of the plugin do.  We all use Ultimate.  At one time, we were using some classes that were only available on Ultimate, so those features would break on CE, but I thought some folks removed those dependencies -- at least so that they could build the plugin using CE.  I did not expect that debugging was a feature that depends upon Ultimate.

**Comment by arthurferrai** [comment] 2016-09-29 18:01
The Haxe debugger seems to work correctly using 0.9.10 release and Ultimate.

Also, I can debug the plugin itself using CE since I use the Ultimate .app as reference to sdk folders (it ends up debugging Ultimate, but works as expected).

**Comment by EBatTiVo** [comment] 2016-10-10 19:58
@arthurferrai I'm closing this since you've got everything working.

**Closed by EBatTiVo** 2016-10-10 19:58 UTC
Labels: question

**Comment by arthurferrai** [comment] 2016-10-10 20:02
@EBatTiVo I expected to use debug on CE, but I understand that it only works with Ultimate. :)

**Comment by EBatTiVo** [comment] 2016-10-10 20:09
@arthurferrai I actually haven't tried debugging on CE, and I don't know why it wouldn't work.  It may be one of the features of Ultimate that just isn't implemented on CE (missing support classes or somesuch)?  If you have the time, and since you have the environment set up to debug the plugin, if you wanted to figure it out, we would be happy to include that support.
