### ISSUE TITLE
Array comprehension with `new` in it causes syntax error

### ISSUE THREAD

**Issue by grisevg** [TiVo/intellij-haxe#232] opened 2015-04-15 14:49 UTC
Plugin version: 0.9.3
IDEA: 14.1.1
OS: Win 8.1 x64

This is parsed just fine:
```haxe
var children = [for (i in 0...container.numChildren - 1) container.getChildAt(i)];
```

This is highlighted with red:
```haxe
var childrenPositions = [for (piece in pieces) new Point(piece.x, piece.y)];
```

This breaks all following code parsing in same function:
```haxe
var childrenPositionsArray = Lambda.array([for (piece in pieces) new Point(piece.x, piece.y)]);
```

**Comment by eliasku** [comment] 2016-02-19 11:09
Cannot reproduce in 0.9.9
![image](https://cloud.githubusercontent.com/assets/3038174/13174068/5a02f492-d712-11e5-9c25-4247fc40e1b4.png)

@grisevg  please, verify

**Comment by EBatTiVo** [comment] 2016-03-02 17:57
For this code: (http://try.haxe.org/#fADF6)
```haxe
package ;

class Test {
    static function main() {
        var m = new Main();
        m.testIssue232();
    }
}

class Point {
    public var x:Int;
    public var y:Int;
    public function new(xval:Int, yval:Int) {
        x = xval;
        y = yval;
    }
}

class Main {
    public function new() {
    }

    public function main():Void {
        testIssue232();
    }

    public function testIssue232() {
        var pieces = [for (i in 0...10) new Point(i, i)];
        var childrenPositions = [for (piece in pieces) new Point(piece.x, piece.y)];
        var a = [for (i in 0...10) i];
    }
}
```

Things are parsing correctly.  Closing.

**Closed by EBatTiVo** 2016-03-02 17:57 UTC
Labels: bug, Fixed, Priority 3
