### ISSUE TITLE
can not reference variable if there is a package with same name.

### ISSUE THREAD

**Issue by giabao** [TiVo/intellij-haxe#184] opened 2015-03-25 05:22 UTC
Steps to reproduce:
0. In a project with Lime as a dependency
1. open [FlashPlatform.hx](https://github.com/openfl/lime/blob/2.2.1/lime/tools/platforms/FlashPlatform.hx#L33),
2. Ctrl + click on `project`
4. Expect: open `project` field in class PlatformTarget
Actual: open package `project` in IDEA Project view

**Comment by giabao** [comment] 2015-03-25 05:26
If I comment out [this line](https://github.com/TiVo/intellij-haxe/blob/4c8fa986d83f868bf61ee2faecec7ab9ba0fa0cc/src/com/intellij/plugins/haxe/lang/psi/HaxeResolver.java#L66) then the behaviour is correct (open `project` field in class PlatformTarget)

**Comment by EBatTiVo** [comment] 2015-03-25 06:34
Probably so, but then you cannot address any packages.  The priority ordering is backward in the resolve function.  I haven't had time to refactor it yet. 

Duplicate of Issue #95.

**Closed by EBatTiVo** 2015-03-25 06:34 UTC
Labels: duplicate
